package com.sensex.optiontrader.model.enums;

public enum StrategyType {
    LONG_CALL, LONG_PUT, BULL_CALL_SPREAD, BEAR_PUT_SPREAD, BULL_PUT_SPREAD, BEAR_CALL_SPREAD, LONG_STRADDLE, SHORT_STRADDLE, LONG_STRANGLE, SHORT_STRANGLE, IRON_CONDOR, IRON_BUTTERFLY, COVERED_CALL, PROTECTIVE_PUT
}